# Generated by Django 5.0.3 on 2024-09-17 17:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contactos', '0001_initial'),
        ('app_tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_ticket', models.CharField(default='1', max_length=13, unique=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_tickets.categoria')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_contactos.contacto')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_tickets.departamento')),
                ('origen_ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_tickets.origen_ticket')),
                ('prioridad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_tickets.prioridad')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_tickets.producto')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_tickets.status')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_notas', models.TextField(max_length=350)),
                ('fecha_nota', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('autor', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_nota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_tickets.tipo_nota')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketVisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vista', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tickets.ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
