# Generated by Django 5.0.3 on 2024-09-18 02:15

import app_tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tickets', '0003_email_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='numero_ticket',
            field=models.CharField(default=app_tickets.models.generate_ticket_number, max_length=13, unique=True),
        ),
    ]
