# Generated by Django 5.0.3 on 2024-09-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tickets', '0004_alter_ticket_numero_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='creado_por',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
