# Generated by Django 5.0.3 on 2024-09-17 17:24

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitacion_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contrasena_temporal', models.CharField(default='Q0pyTgFWc6', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_expira_en', models.DateTimeField(default=datetime.datetime(2024, 9, 18, 17, 24, 23, 308994, tzinfo=datetime.timezone.utc))),
                ('token_usado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_Forgot_Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_expira_en', models.DateTimeField(default=datetime.datetime(2024, 9, 18, 17, 24, 23, 308994, tzinfo=datetime.timezone.utc))),
                ('token_usado', models.BooleanField(default=False)),
            ],
        ),
    ]
