# Generated by Django 5.0.3 on 2024-09-17 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_autenticacion', '0002_invitacion_usuario_solicitud_forgot_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion_usuario',
            name='contrasena_temporal',
            field=models.CharField(default='JVuJF3SXnm', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitacion_usuario',
            name='token_expira_en',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 18, 17, 27, 2, 422062, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='solicitud_forgot_password',
            name='token_expira_en',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 18, 17, 27, 2, 422062, tzinfo=datetime.timezone.utc)),
        ),
    ]
