# Generated by Django 5.0.3 on 2024-09-18 02:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_autenticacion', '0007_alter_invitacion_usuario_contrasena_temporal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion_usuario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitacion_usuario',
            name='contrasena_temporal',
            field=models.CharField(default='LGbWzT9mt1', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitacion_usuario',
            name='token_expira_en',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 2, 15, 51, 479953, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='solicitud_forgot_password',
            name='token_expira_en',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 2, 15, 51, 479953, tzinfo=datetime.timezone.utc)),
        ),
    ]
