# Generated by Django 5.0.3 on 2024-09-18 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_autenticacion', '0008_invitacion_usuario_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion_usuario',
            name='contrasena_temporal',
            field=models.CharField(default='soob6zZklp', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitacion_usuario',
            name='token_expira_en',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 3, 33, 39, 9505, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitacion_usuario',
            name='usuario',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_forgot_password',
            name='token_expira_en',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 3, 33, 39, 9505, tzinfo=datetime.timezone.utc)),
        ),
    ]
