# Generated by Django 5.0.3 on 2024-09-18 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_autenticacion', '0009_alter_invitacion_usuario_contrasena_temporal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion_usuario',
            name='contrasena_temporal',
            field=models.CharField(default='5KbDnEsUOX', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitacion_usuario',
            name='token_expira_en',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 18, 52, 25, 862637, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='solicitud_forgot_password',
            name='token_expira_en',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 18, 52, 25, 863675, tzinfo=datetime.timezone.utc)),
        ),
    ]
