# Generated by Django 5.0.3 on 2024-09-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_contacto', models.CharField(max_length=30)),
                ('apellido_contacto', models.CharField(max_length=30)),
                ('telefono_contacto', models.CharField(max_length=20, null=True)),
                ('empresa_contacto', models.CharField(max_length=20, null=True)),
                ('email_contacto', models.CharField(max_length=30)),
            ],
        ),
    ]
